# Generated by Django 4.2.16 on 2024-09-06 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import support_ticket_system_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('first_name', models.TextField(max_length=30, verbose_name='First name')),
                ('last_name', models.TextField(max_length=30, verbose_name='Last name')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Create date')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', support_ticket_system_app.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public ID')),
                ('subject', models.TextField(default=None, max_length=100, verbose_name='Subject')),
                ('departament', models.TextField(choices=[('Support', 'Support'), ('Billing', 'Billing'), ('Sales', 'Sales')], default=None, max_length=7, verbose_name='Departament')),
                ('status', models.TextField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Pending', 'Pending')], default=None, max_length=7, verbose_name='Status')),
                ('priority', models.TextField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default=None, max_length=6, verbose_name='Priority')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Lasy update date')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Create date')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Message ID')),
                ('text', models.TextField()),
                ('direction', models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], max_length=8, verbose_name='Direction')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Create date')),
                ('ticket', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support_ticket_system_app.ticket')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
