# Generated by Django 4.2.16 on 2024-09-06 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket_system_app', '0002_alter_ticket_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.TextField(default='Customer', max_length=8, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departament',
            field=models.TextField(choices=[('Support', 'Support'), ('Billing', 'Billing'), ('Sales', 'Sales')], max_length=7, verbose_name='Departament'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.TextField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.TextField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Pending', 'Pending')], max_length=7, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Last update date'),
        ),
    ]
