# Generated by Django 4.2.16 on 2024-09-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket_system_app', '0003_customuser_role_alter_ticket_departament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.TextField(choices=[('Admin', 'Admin'), ('Support', 'Support'), ('Customer', 'Customer')], default='Customer', max_length=8, verbose_name='Role'),
        ),
    ]
